services:
  glance:
    image: glanceapp/glance
    # ...

  restic-extension:
    image: ghcr.io/not-first/restic-glance-extension
    ports:
      - "8675:8675"
    volumes:
      - /my/backup/location/repo1:/app/repos/repo1
      - /my/backup/location/repo2-different-name:/app/repos/repo2
    restart: unless-stopped
    env_file: .env
    labels:
      glance.hide: false
      glance.name: Restic Extension
      glance.parent: glance
